# Site settings
title: "Tsing's Blog"
logo: logo.jpg # image from https://www.flickr.com/photos/lwr/5496279831/in/set-72157594159055823
email: tsai.tsing@icloud.com

destination: ../blog
  
description: > # this means to ignore newlines until "baseurl:"
  
url: "http://www.tsingtsai.com" # the base hostname & protocol for your site
baseurl: "/blog" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown

permalink: /:categories/:year/:month/:title
